# this is YAML check at http://www.yamllint.com/
name: BuildWheels

on:
  push:
    branches:
      - master

jobs:
  clear-cache:
    name: clear-cache
    runs-on: ubuntu-latest
    steps:
      - name: setup python for clear-cache
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: clear
        env:
          CITOOLS_USER: "${{secrets.CITOOLS_USER}}"
          CITOOLS_PASSWORD: "${{secrets.CITOOLS_PASSWORD}}"
        run: |
            python -mpip install --no-cache https://hg.reportlab.com/hg-public/rl-ci-tools/archive/tip.tar.gz -U
            python -mrl_ci_tools clear-cache "cibuildwheel/reportlab"
            echo "cleared remote cache for cibuildwheel/reportlab"
  build-wheels-linux-mac-windows:
    needs: [clear-cache]
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      CIBW_SKIP: pp*
      CIBW_BEFORE_BUILD_LINUX: yum install cairo-devel -y
      #CIBW_BEFORE_TEST: pip install --no-cache-dir pyphen
      #CIBW_TEST_REQUIRES: "${{ matrix.os != 'macos-latest' && 'pyphen pycairo rlPyCairo' || 'pyphen' }}"
      CIBW_TEST_COMMAND: python -c "import sys,os;r=os.system(' '.join((sys.executable,os.path.join(r'{project}','setup.py'),'tests-postinstall','--verbose','--pip-install=pyphen','--pip-install=rlPyCairo','--rl-index-url=https://${{secrets.CITOOLS_USER}}:${{secrets.CITOOLS_PASSWORD}}@www.reportlab.com/pypi','--rl-pip-install=pyfribidi')));sys.exit(('!!!!! test command --> %s !!!!!'%r) if r else r)"
      CIBW_BUILD_VERBOSITY: 3
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==2.0.0a2
          python -c "import os;print('+++++ cwd=%r;dir=%r' % (os.getcwd(),os.listdir('.')))"

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS_MACOS: x86_64 arm64

      - name: upload wheels
        env:
          CITOOLS_USER: "${{secrets.CITOOLS_USER}}"
          CITOOLS_PASSWORD: "${{secrets.CITOOLS_PASSWORD}}"
        run: |
          python -mpip install --no-cache https://hg.reportlab.com/hg-public/rl-ci-tools/archive/tip.tar.gz -U
          python -mrl_ci_tools upload-caches --subdir="cibuildwheel/reportlab" --verbosity=1 ./wheelhouse/*.whl
          python -mrl_ci_tools env-upload

      - uses: actions/upload-artifact@v2
        with:
          name: lin-win-mac
          path: ./wheelhouse/*.whl
  email:
    name: email
    needs: [build-wheels-linux-mac-windows]
    runs-on: ubuntu-latest
    steps:
      - name: setup python for upload
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: email confirmation
        env:
          CITOOLS_USER: "${{secrets.CITOOLS_USER}}"
          CITOOLS_PASSWORD: "${{secrets.CITOOLS_PASSWORD}}"
        run: |
            python -mpip install --no-cache https://hg.reportlab.com/hg-public/rl-ci-tools/archive/tip.tar.gz -U
            BODY="$(python -mrl_ci_tools cache-info --subdir="cibuildwheel/reportlab" '*.whl')"
            NUPLOADS=$(expr $(echo "$BODY" | wc -l) - 1)
            SUBJECT="$NUPLOADS reportlab wheels uploaded to cibuildwheel/reportlab by github"
            python -mrl_ci_tools email --subject="$SUBJECT" --body="$BODY"
            echo "$SUBJECT"
            echo "$BODY"
